# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e9802a449a0f5f15500eb5d6c8ca628da9fa257595c5c1497e4ad4aa5493dda775d7b2c12cc6dc463249253a1c1c1d8f4a28266c80920456907c061b8b04867

test:
  secret_key_base: b19a82e1e7c375ddcf8474f9f8b25573225df3058cc22d26114df8ea7d9022b74cc681295ecf226085012fbf8c3f4504023d5f8c4040b2ee893f73a7dc3e3755

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
